using Microsoft.EntityFrameworkCore.Migrations;

namespace RazorCurrencyRatesDB.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CurrencyRates",
                columns: table => new
                {
                    ID = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Date = table.Column<string>(nullable: true),
                    Base = table.Column<string>(nullable: true),
                    AED = table.Column<float>(nullable: false),
                    AFN = table.Column<float>(nullable: false),
                    ALL = table.Column<float>(nullable: false),
                    AMD = table.Column<float>(nullable: false),
                    ANG = table.Column<float>(nullable: false),
                    AOA = table.Column<float>(nullable: false),
                    ARS = table.Column<float>(nullable: false),
                    AUD = table.Column<float>(nullable: false),
                    AWG = table.Column<float>(nullable: false),
                    AZN = table.Column<float>(nullable: false),
                    BAM = table.Column<float>(nullable: false),
                    BBD = table.Column<float>(nullable: false),
                    BDT = table.Column<float>(nullable: false),
                    BGN = table.Column<float>(nullable: false),
                    BHD = table.Column<float>(nullable: false),
                    BIF = table.Column<float>(nullable: false),
                    BMD = table.Column<float>(nullable: false),
                    BND = table.Column<float>(nullable: false),
                    BOB = table.Column<float>(nullable: false),
                    BRL = table.Column<float>(nullable: false),
                    BSD = table.Column<float>(nullable: false),
                    BTC = table.Column<float>(nullable: false),
                    BTN = table.Column<float>(nullable: false),
                    BWP = table.Column<float>(nullable: false),
                    BYN = table.Column<float>(nullable: false),
                    BYR = table.Column<float>(nullable: false),
                    BZD = table.Column<float>(nullable: false),
                    CAD = table.Column<float>(nullable: false),
                    CDF = table.Column<float>(nullable: false),
                    CHF = table.Column<float>(nullable: false),
                    CLF = table.Column<float>(nullable: false),
                    CLP = table.Column<float>(nullable: false),
                    CNY = table.Column<float>(nullable: false),
                    COP = table.Column<float>(nullable: false),
                    CRC = table.Column<float>(nullable: false),
                    CUC = table.Column<float>(nullable: false),
                    CUP = table.Column<float>(nullable: false),
                    CVE = table.Column<float>(nullable: false),
                    CZK = table.Column<float>(nullable: false),
                    DJF = table.Column<float>(nullable: false),
                    DKK = table.Column<float>(nullable: false),
                    DOP = table.Column<float>(nullable: false),
                    DZD = table.Column<float>(nullable: false),
                    EGP = table.Column<float>(nullable: false),
                    ERN = table.Column<float>(nullable: false),
                    ETB = table.Column<float>(nullable: false),
                    EUR = table.Column<int>(nullable: false),
                    FJD = table.Column<float>(nullable: false),
                    FKP = table.Column<float>(nullable: false),
                    GBP = table.Column<float>(nullable: false),
                    GEL = table.Column<float>(nullable: false),
                    GGP = table.Column<float>(nullable: false),
                    GHS = table.Column<float>(nullable: false),
                    GIP = table.Column<float>(nullable: false),
                    GMD = table.Column<float>(nullable: false),
                    GNF = table.Column<float>(nullable: false),
                    GTQ = table.Column<float>(nullable: false),
                    GYD = table.Column<float>(nullable: false),
                    HKD = table.Column<float>(nullable: false),
                    HNL = table.Column<float>(nullable: false),
                    HRK = table.Column<float>(nullable: false),
                    HTG = table.Column<float>(nullable: false),
                    HUF = table.Column<float>(nullable: false),
                    IDR = table.Column<float>(nullable: false),
                    ILS = table.Column<float>(nullable: false),
                    IMP = table.Column<float>(nullable: false),
                    INR = table.Column<float>(nullable: false),
                    IQD = table.Column<float>(nullable: false),
                    IRR = table.Column<float>(nullable: false),
                    ISK = table.Column<float>(nullable: false),
                    JEP = table.Column<float>(nullable: false),
                    JMD = table.Column<float>(nullable: false),
                    JOD = table.Column<float>(nullable: false),
                    JPY = table.Column<float>(nullable: false),
                    KES = table.Column<float>(nullable: false),
                    KGS = table.Column<float>(nullable: false),
                    KHR = table.Column<float>(nullable: false),
                    KMF = table.Column<float>(nullable: false),
                    KPW = table.Column<float>(nullable: false),
                    KRW = table.Column<float>(nullable: false),
                    KWD = table.Column<float>(nullable: false),
                    KYD = table.Column<float>(nullable: false),
                    KZT = table.Column<float>(nullable: false),
                    LAK = table.Column<float>(nullable: false),
                    LBP = table.Column<float>(nullable: false),
                    LKR = table.Column<float>(nullable: false),
                    LRD = table.Column<float>(nullable: false),
                    LSL = table.Column<float>(nullable: false),
                    LTL = table.Column<float>(nullable: false),
                    LVL = table.Column<float>(nullable: false),
                    LYD = table.Column<float>(nullable: false),
                    MAD = table.Column<float>(nullable: false),
                    MDL = table.Column<float>(nullable: false),
                    MGA = table.Column<float>(nullable: false),
                    MKD = table.Column<float>(nullable: false),
                    MMK = table.Column<float>(nullable: false),
                    MNT = table.Column<float>(nullable: false),
                    MOP = table.Column<float>(nullable: false),
                    MRO = table.Column<float>(nullable: false),
                    MUR = table.Column<float>(nullable: false),
                    MVR = table.Column<float>(nullable: false),
                    MWK = table.Column<float>(nullable: false),
                    MXN = table.Column<float>(nullable: false),
                    MYR = table.Column<float>(nullable: false),
                    MZN = table.Column<float>(nullable: false),
                    NAD = table.Column<float>(nullable: false),
                    NGN = table.Column<float>(nullable: false),
                    NIO = table.Column<float>(nullable: false),
                    NOK = table.Column<float>(nullable: false),
                    NPR = table.Column<float>(nullable: false),
                    NZD = table.Column<float>(nullable: false),
                    OMR = table.Column<float>(nullable: false),
                    PAB = table.Column<float>(nullable: false),
                    PEN = table.Column<float>(nullable: false),
                    PGK = table.Column<float>(nullable: false),
                    PHP = table.Column<float>(nullable: false),
                    PKR = table.Column<float>(nullable: false),
                    PLN = table.Column<float>(nullable: false),
                    PYG = table.Column<float>(nullable: false),
                    QAR = table.Column<float>(nullable: false),
                    RON = table.Column<float>(nullable: false),
                    RSD = table.Column<float>(nullable: false),
                    RUB = table.Column<float>(nullable: false),
                    RWF = table.Column<float>(nullable: false),
                    SAR = table.Column<float>(nullable: false),
                    SBD = table.Column<float>(nullable: false),
                    SCR = table.Column<float>(nullable: false),
                    SDG = table.Column<float>(nullable: false),
                    SEK = table.Column<float>(nullable: false),
                    SGD = table.Column<float>(nullable: false),
                    SHP = table.Column<float>(nullable: false),
                    SLL = table.Column<float>(nullable: false),
                    SOS = table.Column<float>(nullable: false),
                    SRD = table.Column<float>(nullable: false),
                    STD = table.Column<float>(nullable: false),
                    SVC = table.Column<float>(nullable: false),
                    SYP = table.Column<float>(nullable: false),
                    SZL = table.Column<float>(nullable: false),
                    THB = table.Column<float>(nullable: false),
                    TJS = table.Column<float>(nullable: false),
                    TMT = table.Column<float>(nullable: false),
                    TND = table.Column<float>(nullable: false),
                    TOP = table.Column<float>(nullable: false),
                    TRY = table.Column<float>(nullable: false),
                    TTD = table.Column<float>(nullable: false),
                    TWD = table.Column<float>(nullable: false),
                    TZS = table.Column<float>(nullable: false),
                    UAH = table.Column<float>(nullable: false),
                    UGX = table.Column<float>(nullable: false),
                    USD = table.Column<float>(nullable: false),
                    UYU = table.Column<float>(nullable: false),
                    UZS = table.Column<float>(nullable: false),
                    VEF = table.Column<float>(nullable: false),
                    VND = table.Column<float>(nullable: false),
                    VUV = table.Column<float>(nullable: false),
                    WST = table.Column<float>(nullable: false),
                    XAF = table.Column<float>(nullable: false),
                    XAG = table.Column<float>(nullable: false),
                    XAU = table.Column<float>(nullable: false),
                    XCD = table.Column<float>(nullable: false),
                    XDR = table.Column<float>(nullable: false),
                    XOF = table.Column<float>(nullable: false),
                    XPF = table.Column<float>(nullable: false),
                    YER = table.Column<float>(nullable: false),
                    ZAR = table.Column<float>(nullable: false),
                    ZMK = table.Column<float>(nullable: false),
                    ZMW = table.Column<float>(nullable: false),
                    ZWL = table.Column<float>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CurrencyRates", x => x.ID);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CurrencyRates");
        }
    }
}
